Repository BaconB0T/suggestaurant, pull requests merged in 2023-04, with the labels that each got.

#68 Sug 137 random restaurant button on home page
  src/App.js
  src/components/HomePage.js
  src/components/UserWaiting.js
  src/components/dietCheck.js
  src/python/server.py
Labels: needs review

#72 Fixed group not waiting after quiz, closes #71
  src/components/Group.js
  src/components/GroupWaiting.js
Labels: needs review

#70 Algorithm updates
  src/App.js
  src/components/ExpandRadiusPage.js
  src/components/KeywordGrab.js
  src/components/Preferences.jsx
  src/components/UserWaiting.js
  src/firestore.js
  src/python/server.py
Labels: needs review

#74 Location picker
  package-lock.json
  package.json
  src/App.js
  src/components/changeLocation.js
  src/components/distanceGrab.js
Labels: needs review

#73 Sug 163 style recommendations map page
  package-lock.json
  package.json
  src/App.js
  src/components/Buttons.js
  src/components/Group.js
  src/components/RecommendationMap.js
  src/styles/RecommendationsMap.css
Labels: needs review

#75 Time Picker uses current time.
  src/components/timeGrab.js
Labels: needs review

#80 Fixes a couple bugs
  src/App.js
  src/components/GroupWaiting.js
  src/python/parallelizer.py
  src/python/server.py
Labels: needs review

#77 Sug 135 share suggestions from map page
  src/components/RecommendationMap.js
Labels: enhancement, needs review, Tested On Android, Tested On Windows

#76 Update HomePage.js
  src/components/HomePage.js
Labels: needs review

#82 Sug 92 see no suggestions page after rejecting all suggestions
  src/App.js
  src/components/ExpandRadiusPage.js
  src/components/GroupWaiting.js
  src/components/KeywordGrab.js
  src/components/Preferences.jsx
  src/components/PresetCuisines.jsx
  src/components/Recommendations.js
  src/components/UserWaiting.js
  src/components/WaitingForRecommendation.js
  src/components/dietCheck.js
  src/components/priceCheck.js
  src/firestore.js
  src/python/server.py
Labels: enhancement, needs review

#84 Update UserWaiting.js
  src/components/UserWaiting.js
Labels: bug, enhancement, needs review

#89 Update ExpandRadiusPage.js, closes #88
  src/components/ExpandRadiusPage.js
Labels: bug

#85 Distance Grab filters bad input
  src/App.js
  src/components/distanceGrab.js
Labels: bug, enhancement, needs review

#87 Fix copy button
  src/components/Buttons.js
  src/components/Group.js
  src/components/Popup.js
  src/styles/PopupStyling.css
Labels: needs review

#91 Restyle suggestion group decisions
  src/components/Recommendations.js
  src/styles/Recommendations.css
Labels: enhancement, styling

#93 Whole buncha changes
  src/App.js
  src/components/HomePage.js
  src/components/KeywordGrab.js
  src/components/Preferences.jsx
  src/components/PresetCuisines.jsx
  src/components/StarRating.js
  src/components/Test.jsx
  src/components/changeLocation.js
  src/components/dietCheck.js
  src/components/displayTest.js
  src/components/distanceGrab.js
  src/components/practice.js
  src/components/priceCheck.js
  src/components/restHistSearch.js
  src/components/timeGrab.js
  src/index.js
Labels: needs review

#95 Update Group.js
  src/App.js
  src/components/Group.js
Labels: bug

#96 Spelling
  src/components/KeywordGrab.js
Labels: needs review
