Repository BaconB0T/suggestaurant, pull requests merged in 2023-05, with the labels that each got.

#98 Update Group.js
  src/components/Group.js
Labels: bug

#99 Fix decimals breaking distance grab
  src/components/distanceGrab.js
Labels: needs review

#102 Remove images from Recommendations.js
  src/components/Recommendations.js
Labels: needs review

#101 Fix change location without location services
  src/components/changeLocation.js
  src/components/distanceGrab.js
Labels: bug, needs review, Tested On Windows, styling

#105 Update Signup.js
  src/components/Signup.js
Labels: enhancement

#104 Update changeLocation.js
  src/components/changeLocation.js
Labels: bug

#103 Update Recommendations.js
  src/components/Recommendations.js
Labels: bug
