Repository BaconB0T/suggestaurant, pull requests merged in 2023-03, with the labels that each got.

#5 Sug 73 Sug 25 Sug 23 host of a group can get a code to share
  src/App.js
  src/components/Accounts.js
  src/components/Allergies.jsx
  src/components/ChangePassword.js
  src/components/Group.js
  src/components/History.js
  src/components/HomePage.js
  src/components/KeywordGrab.js
  src/components/Preferences.jsx
  src/components/PresetCuisines.jsx
  src/components/Search.jsx
  src/components/dietCheck.js
  src/components/distanceGrab.js
  src/components/priceCheck.js
  src/components/timeGrab.js
  src/firestore.js
  src/python/server.py
Labels: enhancement

#13 Quiz styling branch
  src/App.css
  src/App.js
  src/components/Allergies.jsx
  src/components/HomePage.js
  src/components/KeywordGrab.js
  src/components/Login.js
  src/components/Signup.js
  src/components/dietCheck.js
  src/components/distanceGrab.js
  src/components/priceCheck.js
  src/components/timeGrab.js
  src/firestore.js
  src/images/Green.png
  src/images/Images.xcf
  src/images/LogoBuild.xcf
  src/images/Orange-Swirl-Background.jpg
  src/images/Restaurant.png
  src/images/Transportation.png
  src/images/Yellow.png
  src/images/car.png
  src/images/clocks.png
  src/images/logo.png
  src/images/money - Copy.png
  src/images/money.png
  src/images/time.png
  src/python/server.py
  src/styles/new.module.scss
Labels: needs review

#14 Fix main compilation errors.
  src/firestore.js
Labels: bug

#15 Minor Bug Fixes
  src/App.js
  src/components/HomePage.js
  src/components/distanceGrab.js
Labels: needs review

#16 Fix bob
  src/components/HomePage.js
Labels: needs review

#17 Bug fixes 3
  src/App.js
  src/components/dietCheck.js
  src/components/distanceGrab.js
  src/firestore.js
  src/python/server.py
Labels: needs review

#19 Sug 37 Sug 38 accept and reject suggestions as a group
  src/App.js
  src/components/KeywordGrab.js
  src/components/Recommendations.js
  src/firestore.js
  src/python/server.py
Labels: enhancement

#12 Login with google button on Login screen
  src/components/Login.js
  src/firestore.js
Labels: enhancement

#32 Update .gitignore
  .gitignore
Labels: needs review

#36 Sug 31 rate last accepted restaurant from home page
  src/components/HomePage.js
  src/components/Popup.js
  src/components/PopupStyling.css
  src/components/RecommendationMap.js
  src/components/Recommendations.js
  src/firestore.js
Labels: needs review

#35 Sug 75 group waiting screen
  src/App.js
  src/components/GroupWaiting.js
  src/components/KeywordGrab.js
  src/components/dietCheck.js
  src/firestore.js
  src/python/server.py
Labels: needs review

#38 Update Accounts.js
  src/components/Accounts.js
Labels: enhancement, needs review

#39 second waiting screen
  src/App.js
  src/components/GroupWaiting.js
  src/components/WaitingForRecommendation.js
Labels: needs review

#40 Group host fast go
  src/components/GroupWaiting.js
  src/components/KeywordGrab.js
  src/components/Recommendations.js
  src/components/WaitingForRecommendation.js
  src/components/dietCheck.js
  src/components/priceCheck.js
  src/firestore.js
Labels: needs review

#41 Fixing non-progression bug
  src/components/GroupWaiting.js
  src/components/KeywordGrab.js
Labels: needs review

#43 Fix bug where single-user doesn't work.
  src/components/KeywordGrab.js
  src/components/Recommendations.js
  src/components/dietCheck.js
  src/components/priceCheck.js
Labels: needs review

#46 Fix map undefined location
  src/components/Recommendations.js
Labels: needs review

#49 Bug Fixes/UI Updates
  .gitignore
  src/App.js
  src/components/Accounts.js
  src/components/KeywordGrab.js
  src/components/Preferences.jsx
  src/components/PresetCuisines.jsx
  src/components/distanceGrab.js
  src/components/timeGrab.js
Labels: needs review

#48 Group popup and login button style
  src/App.css
  src/App.js
  src/components/Accounts.js
  src/components/CustomAlert.js
  src/components/Group.js
  src/components/Login.js
  src/components/dietCheck.js
  src/components/distanceGrab.js
  src/components/priceCheck.js
Labels: enhancement, needs review

#56 Add back button to Recomendation page
  src/App.css
  src/components/Recommendations.js
Labels: needs review

#59 Update keywords page
  src/components/KeywordGrab.js
Labels: needs review

#58 Parallel testing branch
  src/components/Recommendations.js
  src/python/parallelizer.py
  src/python/server.py
Labels: needs review
